### ISSUE TITLE
Screen doesn’t turn on on DC30 badge after installing Modem SAO

### ISSUE THREAD

**Issue by abjugard** [hamster/defcon30#1]
The screen doesn’t turn on on DC30 badge after installing the Modem SAO. What is the solution that can be applied at the con?

**Comment by hamster** [comment]
![signal-2022-08-12-16-29-49-984](https://user-images.githubusercontent.com/412629/184512845-3efa7932-d876-4ea6-a19d-505f3c6555cc.jpg)
The SAO loads the i2c bus too much. It's not being used for the SAO other than to flash activity. You can replace R7 and R8 with higher value resistors or cut the i2c lines as indicated on the badge (see photo).

**Comment by hamster** [comment]
R7 and R8 are on the modem SAO.
